---
- name: Tag VM - "{{ item.vm_name }}""
  community.vmware.vmware_tag_manager:
    tag_names:
      - tag: "{{ tags.tag }}"
        category: "{{ tags.category }}"
    object_name: "{{ item.vm_name }}"
    object_type: VirtualMachine
    state: add
  loop: "{{ item.vsphere_tag }}"
  loop_control:
    loop_var: tags
